version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: go-crud-postgres
    restart: always
    environment:
      POSTGRES_DB: gocruddb
      POSTGRES_USER: gocrud
      POSTGRES_PASSWORD: gocrud
    ports:
      - "5432:5432"
    volumes:
      - pg_data:/var/lib/postgresql/data

volumes:
  pg_data:
    driver: local
